# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
alias(
    name = "select",
    actual = "//src/kyron:select",
    visibility = ["//visibility:public"],
)

alias(
    name = "main_macro",
    actual = "//src/kyron:main_macro",
    visibility = ["//visibility:public"],
)

alias(
    name = "mpmc",
    actual = "//src/kyron:mpmc",
    visibility = ["//visibility:public"],
)

alias(
    name = "safety_task",
    actual = "//src/kyron:safety_task",
    visibility = ["//visibility:public"],
)
