# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("@score_qnx_unit_tests//:defs.bzl", "rust_test_qnx")

rust_library(
    name = "test_utils",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "kyron_testing",
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        "//src/kyron-foundation:libkyron_foundation",
    ],
)

rust_test(
    name = "tests",
    crate = ":test_utils",
)

rust_test_qnx(
    name = "tests_qnx",
    rust_test = ":tests",
)
